version: '3.4'

services:
  controlexitnodes-local:
    container_name: controlexitnodes-local
    hostname: controlexitnodes
    networks:
      - controlexitnodes-web
    stdin_open: true
    build:
      context: "."
      dockerfile: ./Dockerfile.dev
    ports:
      - "3000:3000"
    expose:
      - "3000"
    image: controlexitnodes
    volumes:
      - .:/app
      - "control_node_modules:/app/node_modules"
    
    environment:
      NODE_ENV: dev
  
  
